/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Wall } from "./Wall";
export * as factories from "./factories";
export { Wall__factory } from "./factories/Wall__factory";
